version: '1'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend